version: "2.3"
services:
  transferwise-webhook:
    container_name: transferwise-webhook
    build: .
    image: transferwise-webhook:latest
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
    expose:
      - "8121"

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}