version: "2.3"
services:
  transferwise-webhook:
    container_name: transferwise-webhook
    build: .
    image: stevenc4/transferwise-webhook:latest
    volumes:
      - /var/log/transferwise-webhook:/var/log/transferwise-webhook
    environment:
      - NODE_ENV=production
      - APP_ENV=production
    env_file:
      - .env
    expose:
      - "8121"

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}